[package]
name = "atomspace"
version = "0.1.0"
description = "OpenCog's atomspace re-implementation in Rust."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://source.that.world/source/rustcog/"

[dependencies]
